language: go

go:
  - 1.2
  - tip

before_install:
  - go get code.google.com/p/go.tools/cmd/vet
  - go get code.google.com/p/go.tools/cmd/cover
  - go get github.com/golang/lint/golint
  - go get github.com/mattn/goveralls

install:
  - go get -d -v ./... && go build -v ./...

script:
  - go vet -x ./...
  - $HOME/gopath/bin/golint ./...
  - go test -v ./...
  - go test -covermode=count -coverprofile=profile.cov .

after_script:
  - $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci

notifications:
  email:
    recipients:
      - gloob@litio.org
    on_success: change
    on_failure: always
